apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: immich
  namespace: immich
spec:
  encryptedData:
    postgres-password: AgB/HkRLj3l2WeHQ2JTmRRHOU2aLvssg+UT5L+PWSInuBkfcFtBnnTl0p1DIa1lhyWxPaI4H+EiAzKJ6yHJIA2H7oeE0pIWCTxpUIpU/Hjl+vcTe0RPWT3uZ26Aj1WSz50emqpJEmxOY2BolBYJWN7hCEYkEzL2GgQLuT5TeZ9Lm3fuO/odR5E0NY4jcis8kR2ApgLVwJ9DTelbr8Cm2fosTgpmmyWmUQfRQvfyLA5h4eRrg9VSTZFxqiQmVHAibDWKMWDiX5CVo+ELJsZS0HTchsuaMShL9Mt8lzS6H56+6Q0H0dN0ZaFcCWjhayj9NfV8mpU/cTlxcscmxU/m6pk6BWvzO8zQLfxH1sdWA1/w7+/teNlL0o5VBZZrd4Yzx/kg8wGt+1RCFdvXLsGiFx5Dp9u8GWoSM0+DObZONkBMr8YB4XTJ9pwfr6RN0J6Cs7vlAyy1uygG8kKRPev0TyyfExLGRTqt/w0xPGuXjoCDYT71MC6AIXHnp09FTG5433/cwmYheNE8y7XcCZTBgfyOrLiZiFIQklhyZ3X4h9hT8mHvP79Lk5SesZ+3d/sTidPGHLRxILIXIsCCwrqlZcW8fr3+PvsKhRZ8BNhgF03FhsSK6XUwdJLoGSThDRCksTHU64qEkHImHThNCgYYNqHZ3GphH93vmbWJb5nH5CRaeX2Cotz8P3LxZ++4d6tkpoMDbjE2wSR0obBj+tYQikSalqVV5l2GpVWv/GXJFYrJ4lQ==
  template:
    metadata:
      creationTimestamp: null
      name: immich
      namespace: immich
---
