apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: syncthing
  namespace: sync
spec:
  encryptedData:
    gui-apikey: AgA3VVDDl8NIkYD69xXYg2MdFnVo3p/6GdxSKYHfOFOG7eF80x4AT4uxhtji7INuUVElHUqKgTs8fBgREr3JotKvVMS9UVKpeYzqIhWoLvAy+ZVLGOnqIDvBaIPYvnGWXthJGB9Z3DG2L1HsvCsr+nG9szZ1eAaQHQ/ok25jBxPhRbk1qEKPwJrZ2DLYBUjdQwcQAngkCoRdHDs5AMFUPxDCP0eT38VysMdl4djZiAVbDmnr5ITVeG5Er50ebrzFANgRx7UIRoMIGNYquxeKiyCEnG3ryPdAmuT5FNin7gxeebYYQ/++DBCg7L1ArvuEyQ46JktsrxFGCCrhdP+l+YaEaaQZkLMVKOUvgGdOgpIQtvt3/YzsUiBuXKqbJbHWUKR+1pR+nUGwV4F+6nnOqRiuDNzogx2XY67GdGg1z+Cs1XKIEpKdJ07dUkfMmXafzPvGXsWMGUqhJydtvacogPq+gZa2kaXluDIFm4eu3cOnHHxljX6OF/OiaGWQLrFGWGTXCTf0MVrpz+N2oYGPHM4A7R/mI5V+bM23oYcJJSCwsHyT9bNecADVPbW9zldPS7TpYG5BIiZQp2nAgNyW1dp2nBqm5Mm9Bl3T60OByhELV1YFKhdQwveRlG3U6ejabdLLEQryfkoexSRcTmkxdRRBxB1rRnWzC78y5r8+gtLYfWdrv80GIO3f30oLob2vzPFJAh3FszVEzRSoi3tQt0ONEJ6jv8BpQ63O6QAuBNjsXQ==
  template:
    metadata:
      creationTimestamp: null
      name: syncthing
      namespace: sync
---
