apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: crowdsec
  namespace: monitoring
spec:
  encryptedData:
    bouncer-key: AgAVieSNiybgDwdge9X08v5/TYcaSiJW+jBxrJ2hTJFpUQJpFaOcq2GT2T2HQ4TIbzKa7ZVelW8LIFxAOLWdcEuTZjFjyweGBBPypanJoUzQasL38FFjaf0dz0V7ZhhuQNVFCOjwQ9rl5aXA/wPHTWTVTnbLsohNtZ4/kVYKSwFp3JS/xDcLmJqnpHyfCR4IYq3hn2xQbzzbBbSfV1oSTX3PKduxxcJS24EYe5Crz5jJkIZZ74l33TTgp8J/s7xuGnJM5svtbjobGE3uasEM7aOdWsznH0pZVlu2y8nY74pWCa/uzgb7u0Z7dJCepEMq3FUtZ03frHAP5F4TjiW2k6fGEW1LlXcJSU5o1tCp7MatT0ed/hv6tpYWdy1wai3Xp0VLMTCZ8Qkr3ety/J23WgVZ9ldJDEmk4XOiQD0kga+nCIP1642eJ/++2jBwWM6Oz31EUzBzk97W4Ahk3egMyzwAwF4JDYUkVYHPvDNxMGaltXVHJN/SxR/4wGwy5w7O5WIXYGkBGAUip0HEPVEQ5sLxDL+XzYvXcKHhzMW6BVpBduZyovxAK4htjH+D/qL8C5Oql+A8rsRQLxjJJy+6LR4JpZBAawFDH9ElSVN82tk0lwdJt3d1zj/i3LWK9wCl6OfW37w6VlIgKPOZdqVY/G0bE/Vs6tLy9fMn5xnTbt/hRsIDlT2ma+LcV97ZQIF5JHUTsowOA//YA+JVSOzPiJJ2WC4qSM9r9Yqhor/BRbsCqtipqc4t+TjB
    enroll-key: AgCRUUlLWUwu9QdGKHHkg/490KnBLFGOfeZClltCpHSKrDWWBWRAdsaFXDGuwHjvfIl2IKW/1j7kMDPZK60aB5USeWaFfk5UjGg2hnrPvpN7fIbBAJJZUWUI7TSoi+kWok1slXWUHHjAfeF3N0mkO9TBI9ds5RjV3x6UlPYy9d25DzCYOHRUfmws+jDFBi05oyu1030/bClAlnG9RhnZosTIVvIk8uGxG3Dh/IBTaq1Pr9AwtunGyIrJphq1WsFOXMA7qf46xqK2vnvYpP7g/4NXz6EH2+Ur11yLzBZxhL30Q/r16ob5MrdkEvkLmQiYlnz5ea8x16XTmPef0VmrFGGy0VNUVGyW810Jeh+jzxc0OXiynWoRorO5tzspixEtjyEJmj5mnnE+luY4MP7RvgmlHTO/Y7jzJWiYOO99anjGlmvnGs8dZUcWPN/e5WkzBcZp+3Y9hVAOs2eX0QWXn/4lvqYFa1Uiz3J4pFEI4IzbBSw2g8Pex4uRJ5qZSrCjRTn0g69vU0olSLNcAV7Nh4jCijItYVxWlQrS1ArfzkvvJtiENW6AamA3rqYBFQJfSBQs0UerTxyqcjCX8zGk0nK4hlOYLRYccf4FQcAMVS6NoxowruX7y9r9l2uSqm3F/nDDaatmDWw0FWWvhIPzf2sYDiDYrMEDaqUg4jYxz6aRsZb5VoKmETl42Kw8J29GXHs=
  template:
    metadata:
      creationTimestamp: null
      name: crowdsec
      namespace: monitoring
---
