---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: adguard-home-data
  labels:
    app.kubernetes.io/name: adguard-home
spec:
  capacity:
    storage: 5Gi
  accessModes: ["ReadWriteOnce"]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: appdata
  hostPath:
    path: /mnt/appdata/adguard-home
    type: DirectoryOrCreate
  claimRef:
    namespace: adguard
    name: adguard-home-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values: ["watchtower"]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-home-data
  namespace: adguard
  labels:
    app.kubernetes.io/name: adguard-home
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: appdata
  volumeName: adguard-home-data
  resources:
    requests:
      storage: 5Gi
