apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: antigravity
  namespace: antigravity
spec:
  encryptedData:
    password: AgBEO+1fTrZ97eRWMI7GApX61IbBtX0EXS45j2S4sWCAhiUXAC2Jxl61iZYKSHewByAwZMBo79q04GnE/er00FbVxDbOl5IDgwY8pV/MKumHgzmFm56gM1+S3dbimCQ42OtKJGux0o8gAwfxJ+UAO74uqR7s27cpH+pRC9o2+J0zoKmdSwmAui1Fps1ujevApUwKniRRtLeSkM1MfbmZC6mCiWU4UVUJjMyl7VPSb4S2Sx+P9YelhivM3R0q2NFnRe/dcmmkw7HsdGCtImcUkzWoCMS/eZAVS6wMTgYULg0QIyrhvdWGDsXibhjNlKROh7iO5CqUQddVwrlDRHC6Ntr4q7xLlhQBeGJ96PG96vSQ6IvS58pU1sH7F4jONbctBMY+/g8UcZkifvPRVzE9vqP4VPHgb3EVGbrlvSRCUz5td68DQlxiSgEiIpvtSfX7YEppmH1nsJWVm0JA4uVsyPxZHAW8QP/66v6MOJAm4XYFpDjwZ078NpMaCaOU0/PrPJrG6EDrkcVIlZb8Irge45rqAKsLMUnlXghLEioimcpu6KWxp3SBWF5vV3OFzsPtZEkvypKcau7VNTgTchO9Mqh/JoJom/XT2w3T6SszB/BCOZn4fQm/Wv4crZOI21/sHxoDzZuAtm3omaMzvxGjDX9le4ntl8dP88z/36rh5wXFhnWZOvI3hLshv7VW+DsfZnXP9pa4e08bt05Bht8g13MC7/2EJ9fq8HBVq1h4xYQvww==
  template:
    metadata:
      creationTimestamp: null
      name: antigravity
      namespace: antigravity
---
