apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: antigravity
  namespace: antigravity
spec:
  encryptedData:
    password: AgA39xuTZz861CdB2YvuQejMWlOdVHz9GgiFebybFH7vY7QPovG5dCNLSwGodXxpuQCueDlsmOs8wpHCAXtXkDoclBMqCROEz4ezlVV9gLXArm09797VlGoBNvXHnJ88c7ksjXLi+sPS5BJG1owQIj45akMZi4Sta7voRGanh3zd+H5nRVq9QyPx6s7VcasMWz6DbAQaSy5ScPgV9ZWSsZYuWoyK/rWMkVb02RIucNkozet23oAFvYUEzp88tSQDdy2jjwyG7PqfDsuGZOv/X3LdHCZN5u8a+mad69uhm5LuOlaGfmm+t07UN+Mu5R2Cqhl6Xql3QzlSGWv/6HMXCwD1BDcUV9SW+C1HBu7okp0+hVbsONIUbhr9XpSqR+DSn5Ys7yZvU+riDiFQDxHfNl2xSJcZWBBH5HG+xv1YvTSaUhCK1FkA1SstdthcanhwfkSPrKu34PYD2uf1WQWgi3aKz59QVJGXrRQNqx5cBRX5DjQ1o9HKiTAw+TCdF9RkmNN5D79u4SH0gZuuVneAc9PW/mdCgoVdoQxToaisg6KRbRHNCgN+6sR9EvXmiRF0GAIfQoHsaE+QymJxCR9Ur5dJyFOh3lkSHUPGKHYUBYd5pGNlITU2WOe7y+Dsb43IyudwW2Iz2iz1RcEMjnicMhQVUa01CxhIwZSQ7DPWOy4hWqq2K3U15Q+TVNQZBUS3S/+/WT7UKU1ESyLHtdTQgnNjLkpDr/1U8Js=
  template:
    metadata:
      creationTimestamp: null
      name: antigravity
      namespace: antigravity
---
