---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: uptime-kuma-data
  labels:
    app.kubernetes.io/name: uptime-kuma
spec:
  capacity:
    storage: 5Gi
  accessModes: ["ReadWriteOnce"]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: appdata
  hostPath:
    path: /mnt/appdata/uptime-kuma
    type: DirectoryOrCreate
  claimRef:
    namespace: monitoring
    name: uptime-kuma-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values: ["watchtower"]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-kuma-data
  namespace: monitoring
  labels:
    app.kubernetes.io/name: uptime-kuma
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: appdata
  volumeName: uptime-kuma-data
  resources:
    requests:
      storage: 5Gi
