apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: uptime-kuma-ntfy
  namespace: monitoring
spec:
  encryptedData:
    token: AgA+OtaQCzn5inaHR+WM0jpcwJtweIQ7djBf1ozGrO3UO0X9GcjuPkw9aanmnoTEPIoo8d4dzQQrPtZDs0+B4xARTsKY/KoW8p5Juca11CzfnUOMMIG4qQnYeduNdwJxPHjPAS2Y0iDAoZBqvrbGvFn5ePtl9ckoxCpJEao79Z674topJ4Y5yLXeHK2+pP5IEOf25TRF6S1U1Tfc9z6BUseaKjfb0/x6lvdkF2yBlI7Fb+bteHvJ3vGUwcGqi8P1luyAgM4RuvLcnyPV3dst7k3Zr5pBll6JAjY3aK2vQOb6BpdsU5k3NQ67fcJZiiaMDhrh+RbVp5lU6tIMMN4nJ4bQEJ1P4Q1TLGvqwbLSKuAtUGC8UG+bzfg3OuVUj8Ej13/jii69TRLge4/D2yJEb4ZhrK0W7OdeBksLkWgag/C30V8skSXiNI7GRtoKIHD9vndYmfkMn2PxbmVqbIoOznixtwwiauV4i33dlFzI/DcHMfjP2PGIZdtt5pXiPcSLATaxVahrnM6zKVYyWwBXZgKDq5AgO1s7FZbAmxPOi+EAX2ECZy9vFEsPVYU4uRPYKcJW921Mx9Oer48MxnKB28ZxOjMSp2ueEvcjCeQq/32f+HSv6ezvNhgfNhB2Unq7QE6E8ta3XE9rRBbWaqRD8Yk/rjCYCJrLAgEslwBGBhubfA6iaCcp7cyaIFB6GTOm5/VqckAVv0VKL8fVjDN1qNxZBWaCDURNtkDQuWmNxDWRFw==
  template:
    metadata:
      creationTimestamp: null
      name: uptime-kuma-ntfy
      namespace: monitoring
---
