apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: caster
  namespace: caster
spec:
  encryptedData:
    postgres-password: AgBm92xp+63GFHvx9RkxUxX9vEMRplgSzk9SAqoUARwJOBkgWvjrt1n7llODWsjhkZZl7HjJ5xCKm7IXg9Q1xXIuB3T5N1p1p7kA15/hUkgT/6Q48CGr4EIEAxkVt81jIg5OJlybsNVgcM08Nbi4iRmSA35k2jrSUydVT7A5dJeezxUrWzkXL84ZWDPpZ3l2EupKFFIT+lYnK8NEaTtysxcb7lAW5wg+ypx/tDJ1PVQ+pPd8rWwpx9HQKdfDMpfZ+OvZ/r2U/Gm+W4qghft3DuGA210hesvRe6OZzLNfQU5e77w9FsnAHq1ueoSgzt1YGOsORrmBde8SZu5cm/Ma/ze1JJXbykFWwZswvV4cD/zUcCN0zpSdGVb7mvR0OEcparcH5DDqYUjWjLxNAVEhMMfR7/WWdPgzNBzrSKhlrXMPklrIcNgAT58NxpfqlcB3KCkI7tzhI8Oe6p3kd4oOhXESjgGyN066aGbcmq6D2YZ7iu/gIG3Z7jHcw09dplCiSPf1X0W/0gPZhKMZlRGusBlhAyF7+2T75hnqsOu2wGEWqnAGmNCh5dcaNwf8llCT7PvuxEsbtkIYd9nepH/MccySZtw8osO3Pr5dhju70cpc2SzMltTGqRsB9JCZWwQdyC0FWRu9eJxtkUwgbUf1YTCqlzyvP56Wp8BEFxzPZFZ06Me0p6Dy5nlThHbaqhjvM1vEWjxfmwKh4SGMLJRh2jrmzWcoXGxThH7ySDe16IVi8g==
  template:
    metadata:
      creationTimestamp: null
      name: caster
      namespace: caster
---
