apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: caster
  namespace: caster
spec:
  encryptedData:
    postgres-password: AgB/I2p9TaxblkiTbvtVLOSVujII4dkqJ80sA87cnGZP9UNcP7tl2bNfo8e+vJ48H+ZMBT1wYObaGr4ZYp9LzAOCAyNi0ZrnMEuEV2W+4dr5zGRc52ghdSgzWsoNOp5AIOxhgiQuxQugt255SYFD/DvYd80ALCOEuxE+jstUsHZQb61b5x6PqKU7ZH9nwHjYRW/ZE2jXsvhIHxVudm/05PER+EcyrI+IPLKMJqh8cm1nLfHetXta21/xRbCG2Zj8IJcEN2Q37aJZ1HtUteiwF7oIHinToYVIr+QbGbbz9PdF5UCjqTv9wW2CYOOr9r9Wvqvfcu0LCaWKPNfzF/Cmo2eDZwgPNP9mBIsI5zw04O8GD7HpLfiuZ3Zjf1comcZ7s4uZfjRqM258MP1qqDBUIGa4XDjVG8hWSqUcbOExsDlVjrLla/65vbVhoRCrn9FMvEr3kjjOZOV6Hg4kLEsTX/Pbamc0qoy4Lgdv6/IOFVtxW8sUmE/bOlutgEdrvXrUNxiUgSz0vs1P6AtD0OsPgSFFVR7cWPgxkOw909Jv+1Z4RHwn3EMZ2Xm8JLtGKfkOPlxNsnyYoOH3ZQtaDcNyse2qKsnzcQTfAwbZPJU9rQTrO6ii18v4wLelvJLERcOom6j9kj3Jz8ZeiVGQ7cgiGHnm5XaQqa1BSb/wLVO8r9dpgQJRLpMlYm9nRVq7cAWAkeO6E3UtYehD/SJ3XYa6ufb8Xdk8Y2dbCHmq52PotJuoww==
    secret-key-base: AgAYXT3kPlxxG6IrL6IwuQuBBIWDHf16oxjsC9A0SMkU+zXqvt6Zn9jDeq4WlaGrG9oTUrsV+4Ls6SwR+qqEQTtpcAHiAYLJhORE5JK8qLSy+5qCGOlpVQPmAKlQnA71oq9o7qELJ6MD746OJ9bLwMYpjC4TChTinP9jNvChzOGzNmIPpu/v/oSWDxCoJTF88mvbpezc3n4ajlompk0E38hYzUiYdjaPZbfHCc35B94QyW+WLTlaz+5p8d3afIoHIRcr8q0v4fB0Gv+kLyLNfdaQGhvI5OCZfkk/sug96R8kyddlxoUWIF0RPAq7JAT1aFiwP+bMbpuvEGg6JwuE2h6qIyB3qf+3bSIXrZGlZnUMJmkcIqbvlUMJ6JCx2EhsjPdsaSki0JMbYH+xwtAr+cOiV9xA3XrAayywU2C3RgIVMH4kL512CsrnL7k6+gYZOKwWsJq1XS0DANQXooaNRXUsrkqaYDF4HK+a+XX5fBejYRFuAt0UwdQS6tKtToViVcCE6LVV/7/2X3EqoC/WIc8lMyyiQl55SMmx8RvFKXpI5Lfs50OIS8lClDsdt8336Zvv+8x4QTmcVNUM0HnieWp+mDZhDtNXzNcQ2jczi3gfe4ddI+miAyCKIhlPVDjBzX5zB+eqSqpMae/0WdpTY1h4MATm3ODIFwq9hPkDw5P0443CGB9IWaeJNa+dHoJ7fYzoaJq0ks4L6mVqjsmec0dyjXusIXKE7xwJK9xxLzL+/kYJy1WfDlRk/KiifJdGQVwanECL00eoeQTSZldRTOie
  template:
    metadata:
      creationTimestamp: null
      name: caster
      namespace: caster
---
