apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: registry-htpasswd
  namespace: infra
spec:
  encryptedData:
    htpasswd: AgBnwN9Qmr3lENduSWoiUCXdCgRaZY8PwakI6AI1HsbqGX7yXZTbDLsresXtVY/7Yz+QweiMc2ZzQCfr4uBdB81FyvckEC6eRWRpNPfslhADXIIYRSvwtKgjedw7X9oEIgMw2WqHmDHah4W2leH4RZpcaYw4do2Nf2+eNjv4DmuHqtgLb7bCg3UJngmAN1tKLcD8Ve1GioYclZD5IGCDbDjncklZvBBMG8PTgjNKE+AB58J7QcefaB5f0r1/FRebtBVLa/nTnLnZAzY2Q0QD6w8li8FPIuznaMYTGMQiLC8Gzy/hgoCWr1EJ48+XkaxyHseHJrviViR5NsYlNiVEg//kFAgFrqUFj5+OG5zolDVDXoIeNw2r3zkEyt4f5ES7Dtfu4jIJIIHxNynqYMGHkJpgpB13uj02ldiuMs1JZBWFFRlegpSScWwQd+561mNZkYz/f07uyElEQKQDLRABvuxvhBzrQ6GrXXuYfftaSZb3XL7Gh3yXDe6D+Y9foKusm3mHg+NA0/AbZ7npzieAfUBzusGAyDRHEHgcdfzkmngR4fqvQbciyfb20N0NPBZzglQumYDI8OdZrzUCqEoo/b7R1GNNeK4bGhav2LvW6ap6bC8n7A1PP/SpPV4tsuvJasExLPdLi48vbPhiO+ac0bxTmfw1iXWYfmlw8hOYdIjeUZ2t8Rpfi7jfmWa5QtTGztTUDV7ZdnH+mwb/WSoZWNmue450sqjzCNJtBXrvk+jaVwDCWe9lVhAVGXOSBV1xRJDtFvHFdSyPsqS8zCRQmD9ztWc=
  template:
    metadata:
      creationTimestamp: null
      name: registry-htpasswd
      namespace: infra
---
