apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: homepage-widgets
  namespace: home
spec:
  encryptedData:
    HOMEPAGE_VAR_PAPERLESS_TOKEN: AgBFE9eZ+T9x4q9fEw8/gKWJmv48nwyE9nPDWMKjL0JYItZfotqIOtW4EdzK5oOqZZBpbqwM/G8P+W9lETZxrT7mvSHaDNCEQZLP6RPaVCdrO75LujOq7LHn+p/spAXc/en1tcehaPDb+YZaG8xhr1TIWyA2hQUX1S22MmaljoEQ+HeQj3IZzKsb4jiQwvFRko1D8tpUoz6HiqIIyqFikeEugvOFEfF1NPMuF4TRy0JhNCYQXDBzPUv+eWh8tHLKJrUMZ6dLp2RH/v7Xj+oMkFJK661SOvepUvk4Nk9PyeQSQ1MgGYs5hhkwKWL3nuwrmR+qWGQDxMBsBkab6UpAE+fG8YVqpm86DoHGFerBMWlvDL0+dMlCpfvQ9w3Pv4ssxFWZWeQGgtOgDpdOK3cDzc8PF4LAA0+tCTPTNIQDjYnyfXby/RhZ2PrMb3p5AG3Goa4Amq5ZxmjIIME6IwzmcZggn9BjbM5+cGPlCxjPnCTRRntpBd3hv+Hjg/aIVRETQJGUsVAnSUnjQ8brXdCLG3PkCcL9NKb+TSdawgIH93TQOG0gJyv8lyR+mSPBmmVs4NpuQsfTWScNZKCup83AZBH5M2y/CprBH5xlIdDSEVH5C1jZBFcQBy3Qeae7g/OOuujIsktjdMr/vBka84WpMqpECduGFYgRU3xxuJGJV+FDHCqP77Qnq+68ryrm7RsmOYt+9cvOGPjVbsOAYOSLyrZ00UkQDMhvvmhubJD1ifWtH/9FcEWeBkcb
  template:
    metadata:
      creationTimestamp: null
      name: homepage-widgets
      namespace: home
---
