---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: beszel-hub-data
  labels:
    app.kubernetes.io/name: beszel-hub
spec:
  capacity:
    storage: 5Gi
  accessModes: ["ReadWriteOnce"]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: appdata
  hostPath:
    path: /mnt/appdata/beszel
    type: DirectoryOrCreate
  claimRef:
    namespace: monitoring
    name: beszel-hub-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values: ["watchtower"]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: beszel-hub-data
  namespace: monitoring
  labels:
    app.kubernetes.io/name: beszel-hub
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: appdata
  volumeName: beszel-hub-data
  resources:
    requests:
      storage: 5Gi
