apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: beszel-agent
  namespace: monitoring
spec:
  encryptedData:
    hub-public-key: AgBup8sqkxlzvntJnkXH/E3aGQzf78eD42t1EKm8XaTSW+OVkgupRhvtJHXm+AbeYw+nBN+qRTkFQuB+lpiu7Kjhje6AM8fo1QYQUk0lcve1nz+Yypr/gacMNDNVppktsHrjSXP07DWVLd/DI6jxk77Vsg4g30EIUG1IL1Uwdy0WdF/p4U2VBGTs4bnIYc+PnbfU1Aia4yR9MDt+4RcXMis+/iOXrMD3AtW71gKFnMaYSlIFM7eQEymK8eqnpX6d31A2/u/nBOVj23zF/RNiKLRACsAfoOZkdunmGePrS3CCPhLUpMpQc8HQoCvcg5i39xLCiPOfls0g67KcWLzrs7nlaSlG1uZ+RiBu62oyZ4XflxxnoCOiS4jLzDYOQNT91uCZrhXGPgxmtdUJ9nYXPinwDkB/K2OCvEEMGWWKKoDcvJgsl+065cXzR4PCrAvZhY8TQ38OKVWGhUTmIfQK9S4qfWU5OzzWJsoR0z2hHuIDf0LRRYpSu3DcmUDUHRO8JiJ/Jhl6Bo6vOztNvQ7IUvarJUkHd+cbCpxgzrmbjxQTbYM4m0ihYeqa+JFtfSrFigYIvpTr1YfZ8KKQI2QPn81CKNp2nwM/sAcm/aDFm+RAW+ed0TsqpyjzddFILlHxiiqErQJG73FG5OiCvWfrZM2thPJeWjv4JsXglab54pLjGB5k5N2bBQfeQyQ/yqeRIPPwmWGStwe1QzXX8AIzxNK7xhq7J2tgXrrJ7EYxtsd+tiQtrBfP7NOwmLgywLVNIqFELp3wsLN/s1r+tIBjTqWxSyJg9RReYWDPauVKwMs1vg==
  template:
    metadata:
      creationTimestamp: null
      name: beszel-agent
      namespace: monitoring
---
