apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: searxng
  namespace: odysseus
spec:
  encryptedData:
    secret-key: AgC9dlzkQpgmlmE5peLHCQTxbEbKtSI+vPpvYIof3TAesJBbvWTUafB3KpI/Jn1OxDy57iXdg7i2fgLzAEBnfWtoxl1G6AB1ETjzibV2h39TrONwthwjNKahwnd2TUA+IKInVRkRRjBonyWbtM6euSzeXn1IlA1N4ka0b2r6A6oasjABxqb/pXyvVFzDeAMPxUUosQ8qcllCz+pClI9mNG9O1P755oBcYWEQspeffygiWNPAoJyvnJdOrEsAdpdMd7C++mm22asuaJRerFi84DR9QBOWiG3ixrAhHfCALJD0pY+oB7+7jmB2NWA5aNbNOOi/z90VscLtOQmo8paoWZ2huD4CQeGtssC+pV9LMB9rqhr6yn9htDmOytbQpkDmQsceEVDeNpPr3Sfag+YBqb83kZGUwZ18JfzwK24hBhdanNEPtPw5k5jdfAPDEjwySgDyRxLf/0ep5CAMCi7/GC3b1PYCnlPGdqIiJgBj/YHdBmuvbKw76eoT/Dmf5Gn9XFwlOAVpC2VDBAPEEH+o07XwOOFDFQYVNrrpyCoTXzSkzLck3kxoKMBKeZNns84552x++UCy9X4mOfShuyMFgBkIHgJFwMDPY/9WXDzu1fVGhA7hiIZXanKcO9ddQhLhGnhriT1eGaufqPkedGNEEbdzPsQSMQKPb2ORJwLEOmyZcNznq4XryPVdgZTtg2ODjBNF9HL+KmqKse2MvC0pYwUqA47QDyc7/ys/ynDEcex5ItEKeSQlkzgsP776Gbaj1VO19hXShaZcSVQwUWY=
  template:
    metadata:
      creationTimestamp: null
      name: searxng
      namespace: odysseus
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: odysseus
  namespace: odysseus
spec:
  encryptedData:
    ODYSSEUS_ADMIN_PASSWORD: AgBahsVryjMzgaXjt/VesBHj3+Ay0UXrQLKtX2d8Ny5tTQg7CJl0qsKq7MD6yTGWLMbGjFWN9Qsk/egE9plKmKaxCZbWGPhHbcMR+xAenBMstPdIUUpe4f4URnjpw2XWEJFARS3hYI0OwNCdiYQiGhOh1IbqqKEmO4GEFUYA4jO9L2sktZGycwRRVPHe6oNbx//NqJvgd6K66RjLGN9rJi3xW8tz7olvTjYU/Wxj/bJadL1HAMNG4ZN3JKgirst1mbLlvfT8TnD6e1lfOVdVVCLTeyuJO+Ml7HELuDZPAqDoKjdKZvdRmhPqAnZzreu4dLYnoG/BYsi4NdmlUGOtFjn9vUultpbeCY50lcRgovStpW6KFjEz7+KNfDpSP9pwyBT/xuOgwVvs282d6/U6NwGChGp3+UzjNWqS2XW1XbRJGiMHh9e/qSlNoDq8iCQRgI/uIGCsNURl4BjOPBMKk3avbPmkv5VmOWfkYIPmIlUc3ApvgUs+hMbq+gTww0g69O7xn68T8z+AK6YaInL2kaxKHwxOzGxiWXlleYzCPd02MnJE1HRtd+eMMGxrRBULDagmRGKYyIp9djn4XHu7LtTAp13vfpcZK+Ev2HGa0mhKvUs5YvJ67GgtiJnKE43oGYZBJbIlzF+wpbdsdBg8vurOjXa8OHpE/Egn4j9vtER3FktnYhBkwBfFTMSiqmdw+yz6VGxnJNdGt0vIgmJv1bmFWZ5i
    ODYSSEUS_ADMIN_USER: AgB002Qkoyz5KG21eUPFFQPYRHMr4PdnLxtF4s3c+hNYAwzVRtlaFAtQqCmEsoOiSJkHsqyBsgNQnvCbpxJSyRBxRRUj37GvEfuT3BOY++HqsRgrv0/mbKE5Ev7OXjeXcZYMssn1NQHDtaQ/nGv5GJox6ZeSPMz0ui60fj+6wjPXdUiBY/uZ+odcfF2FWAzkk84M5rCb9ocrjB8EUXd5+9XLlPyxLASGCZvnbZvZx2XowvujgEEDjfYgOASSlIpTY8wGv6xe9aUdaEK/cbgcxfl/kIs4KAQwPn04tGNS6evmGl9v1t+NW1WUC8xIVwfib7bB4qZnHaJJlZwBiUONr4xow6G20MQ51s86d/muyl4kNhq6ZeMaAgt8lEHXWd+O9aLQtyXKcrlsx1LJU7VdUmW/hR34GuQm9XbxzxciCClbTTUJ7t6JzNY7fiTf6ojeWuh9APQ+fp/w9Kr07g9agoJPXOwrEEmiQ1RAr4827xrIXjUnh6YxNHPDwzTNGloerjyjyYFKNZOxxT69SJn+W/SNG86UO40O+jQNW/CJ5002C678N5VLZVAhfTtrfQtrfPXuBcEuRuUX7EknJfeFUsBFzjI2hndeK4lcC/A6y1iP3j34SQsDPOhEK0Akj7FRIcT/Nig6mG5bdaDurmUbFG3Uu4eWrmuOVga6Js5mXkLCTDQvgmbkaHRT3NkJSzDFV1kO7tXuMA==
  template:
    metadata:
      creationTimestamp: null
      name: odysseus
      namespace: odysseus
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: oauth2-proxy
  namespace: odysseus
spec:
  encryptedData:
    client-id: AgBxwxHl5e/iBUUL3vw4vOg0SQirG/tqHJVpGU8R9k1Pm7TLey7Vum9JmSLJshLZ5qkJTEksOh5jzYzu0jvhHs62zubaUx9s0ToEf0/Q41lvhaW+9dwPNDiupDFvG1gyX8OTDigIx1L6jEZnZAe770BG3a67mSsQzoqOz/a7apGmk+HwWLFqsKBafO9ATQLNAGts6h0TdVgbjaTs8L2c35Cltdyr7NE9BvpgXHVW4DDczmxpvW3lLxT+uXqLAaV6+cTsxVA/KpsfriAjE2/2WLUjJD1kxtgWHDrPe+COTwCXLzzbWKrPu57C+R8zhL3GI+niajzfXZ76vYz6oJU7vut8Yhqd7Te0JGGk2VFHHJI182WIMluzxlbpK1+XMKGp2cEIbHf0m7wBXnrP0NjNU0o5QqS5uhHshs39FsbmPQBHQWXN3PvB2U54OZPipzIwhg2uBxHZkDorNl1jWqePCdcb2+wxe6DbFlpbFesrSUyj6Kc161nULbjn56sUBSc5kCVzwBQUzkrBCGYAyPp+sDmgqDfvs+QV0FA+4xD9lUDe6+CfZO+GyWXwy469ZqEPitJmjqjSLK4NiOWqCKD43zaoLK0yYw5redcAzt/F3qSCUWJ39jfUQCyWvnaksQby7KJ1qKbaHrLLa87QNeo0HgAZbg/iRMyieB0y36Jh3YE0fviApyUCTmVCOHiRCXTLqf7+jbpuok/RhA1VGynLFijgAIWOtbljsXrX86QP9SeGibbPZuo=
    client-secret: AgAIWNqWdetzggNMfPdhBHFlzMAoNl1GTRtln9YecE5SM7g4IW90ysZxi4LceaqvXhAES6U37MNgpSi1aSZhd+SsWwcDP+LhBdLSG0iA9mzBSSv1v9tXpn/KEvjQtk26qaxRfujzWnbBqukJvI8wQQo/Yz//r8ZkpjTJHekySytIpjmc2buITFHm1sZfoFdN6xYHNC5LOmmI1v2XO4+fqDOXQFvr58IoVcPUe4Z440h5XqicUkk8D/DzwjMmoWGTlHrjCwwtXxcdirfA4Mt5URc0mkz18dJNiDhyKnq++DCB0JlMQqCGow6ORbVa26jcxJMSbY26+DJThTOWL3XdHJOkH8AdTo5ciresZTElyiZSC5elpsLdm4Oa1bBiUiulp4bmCzXkT6/Knwtfuls39B6orzfxU23ThtOkq5bunsHbOQF+B8JWtUbv7z1YXS4QTyx/rYwrJ+8C1dvIR5qQMoqe24VIdOBcNU6zReX7jvpg6cECunHxMklRK2KnaiCWjzJsWP9pMHm/DOUb5sRBPfa0VYsFx0bUi4HEvl+EfM/3dKmCIlxNztNVn1xPPyLbae7d5D22kEszbdahATgBPbkRRRV4WjeFwje0/qGVjKWff9y8vj1py7h+XqZkj15YKkdU0z5PFN3LZUMoPmARbVLP9xwKBR0OIf7zK651mDVhhIynZc4N7XDMv4gCcXwo3B7hyPQuCcOgb+RFqAehk8Sxk7LwZGacY8M0oHsL7Z+HAA==
    cookie-secret: AgAu4JiGzPcWFzvF4wgI9ErFCGDSUhRHacpJtX5ynhrWRr6RvFy4NqaGsTzWXKaO6KrYZ7FClcIz25XR+dY/UxMxFG4XKls09AxI4MnCQWKI+UXE0WcT38V0aG/tTKn+izRGwZ4eXfdrIuD8qzjs8ScVdZs5JJKN7vIbk+K0zBaNZ9s3L5XktcefrN0LxjFfulTD2ePcDBmrVIAIIMR/HYJ4KrHEbk4qqCmz4GuVG90lmLNV4gy7x+U2QJFQntYNwsVG5wKsRr/e3b3Cvn+127XN13Y5SXkEgBQIhQwmg0HOQ628B+dM5qHXkC4QAAVUqKAg4AFhf5YLQwQNihPrKyIqm8qBRtEBIxto5CO3uobGwCnck/ba7Gm8J+xWI3IKnUviyCgMOuFf6eL/F/TNqwcTWRR6d9QTx6QeJ9MrjFG0NElk0MotiGHrpFsJA0gMxWW/prHMVhtXRZ7t8MJmRONhrFPvHCy/MrKcWJeETSzA6mMS4LYMJuTLKDHbo+uhBr/wKn1jxlNC50ejWXSR/551QvIiKY3ygoJ1U+Gxx7JlGhLUuYF1Z0yOmhlAupoAcFw25OMmZRRpBe3AiqKGy9gVT9X7GorLd3DGQsXRIm9GsgdI6mto2MYAm12v7IZjffX/4wgADMH+BAE1cJWDQBXO9NV4z1tQNuQ6Xu3vTdRagbEkl/buhvkgliNvw5Ue/oONaoQgFezubD12HC3oKWUY2lMsuhUd661T2tG5wGPZ1IDnl2Zj+vwBdi51NQ==
  template:
    metadata:
      creationTimestamp: null
      name: oauth2-proxy
      namespace: odysseus
---
