apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: searxng
  namespace: odysseus
spec:
  encryptedData:
    secret-key: AgC9dlzkQpgmlmE5peLHCQTxbEbKtSI+vPpvYIof3TAesJBbvWTUafB3KpI/Jn1OxDy57iXdg7i2fgLzAEBnfWtoxl1G6AB1ETjzibV2h39TrONwthwjNKahwnd2TUA+IKInVRkRRjBonyWbtM6euSzeXn1IlA1N4ka0b2r6A6oasjABxqb/pXyvVFzDeAMPxUUosQ8qcllCz+pClI9mNG9O1P755oBcYWEQspeffygiWNPAoJyvnJdOrEsAdpdMd7C++mm22asuaJRerFi84DR9QBOWiG3ixrAhHfCALJD0pY+oB7+7jmB2NWA5aNbNOOi/z90VscLtOQmo8paoWZ2huD4CQeGtssC+pV9LMB9rqhr6yn9htDmOytbQpkDmQsceEVDeNpPr3Sfag+YBqb83kZGUwZ18JfzwK24hBhdanNEPtPw5k5jdfAPDEjwySgDyRxLf/0ep5CAMCi7/GC3b1PYCnlPGdqIiJgBj/YHdBmuvbKw76eoT/Dmf5Gn9XFwlOAVpC2VDBAPEEH+o07XwOOFDFQYVNrrpyCoTXzSkzLck3kxoKMBKeZNns84552x++UCy9X4mOfShuyMFgBkIHgJFwMDPY/9WXDzu1fVGhA7hiIZXanKcO9ddQhLhGnhriT1eGaufqPkedGNEEbdzPsQSMQKPb2ORJwLEOmyZcNznq4XryPVdgZTtg2ODjBNF9HL+KmqKse2MvC0pYwUqA47QDyc7/ys/ynDEcex5ItEKeSQlkzgsP776Gbaj1VO19hXShaZcSVQwUWY=
  template:
    metadata:
      creationTimestamp: null
      name: searxng
      namespace: odysseus
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: odysseus
  namespace: odysseus
spec:
  encryptedData:
    ODYSSEUS_ADMIN_PASSWORD: AgALpNm1sMme0n+q8pqBrOHnNzeSrEz4pAPwuhZ6Vx8oLimRdPyQy3POwjXQ/xgp5MGFlqE1zuDsax5oTAxqE2EMNjbHBYbD/TrfQpIQ+M5kwwlEy4I4bKRJI5WtmSPjzART15+HstE2BR+hSgSi1YEnEYnkvmO8bikTxRvYODh1pArRcpfOUsxrVbxbTtG9ezpORgRhLX8wc5pGEtvD/FA3Y0KGjAgpZzaIkAXCodqA6aBxrtwkpyrqQORRZyrDNvwL63SE1t4Ou8qB3yNWGDPdQmdlsoxvkmRE/QBvqWeRd5civeadkoifuh2kqRCtn4uFGmm0PZJtb2Vp2DKj7shrMRX35+SrFdlJj+EoM3FQLP4AGJt6fUYyzdTwuOIXDOHn+DujZ94B2PwmmfEVxVXZ3RY2dy/n5Civ91IjNWrVS0RyK034cBNDb6msXOjT6YtAorJkt6OdJv2mz3UPtS8WMSD9mO1kX89G458R5evebN/lr2qEXnm8mFeVbIIs8FQZU3D5OKmCuBMVbqDtrlV200Hc1gtOtQm+CaC416S7aIJtuJKcZvO91TnHE9BCYEWEyxnRMrcecveO0A0vOlEwug3QpuwmBlNL+4857MbtFZJNEQxHJrIaZi0OZm+gdKXgqx+wxeTIlpti2cJFS/3Xittwk1olWJDLflAKzUIXQLD3t97Zzdr19wJO5B6+GbRjHfAp7xuf+lU4igA/2d22O7NbIdWHSG1mfH5YPZEYGGXQieP3+3zf
    ODYSSEUS_ADMIN_USER: AgAnFrN/MFJ1iBodNN6FQ58nFNfoX1ezKGKm5BFmlF8i1UmnIxbkP1YJPJtK3hCdpTrRr+WN/w+bhwTgD1gn8eP2dsnbzW1DoPtmyDK34RCYzAzC9y1bH+sj5bauRkaN6J/HseS2JOM3FryW0hBM4SXBGJG8UK1nlT47i0BPE/+gLBWRn92qEwmzf/Pzruj4gbM9L7S9LjiUdB3+uW6EUlN2Q6Qxeik6pCe5wyF5IrG8Q+uBHFJs9G5KWgyPI89CVQCzlN4uhE64zs7fj+yQgPyNlaB+KkXNdXnMsQGpnqq0cepM3z5iwU7Jmw0AjB7zx4EEfh0c9CLD1uU4PmgApqyhh8roeAnI5zZwcSw3jPJc/lFA3S53Ax+uigDnpubXS7BKQ/2dE8IpOiFE/C7QE/UGnvU6maCMEG67U1ExjDfBQZBJqm9XSq6Y35P0qCC+KyLKC+l3uX/ux4bqAbJtHrhcBXZYRUakNBwQOr+AVVDtpzorcAwJwGO+boKZBff5JND6RhIn8oqjWQbCPpmubC+fxIlzfHx6FpS35AYQzjX0yfG4PWSUYvpecZgvTt42ORgUHXUSSr93kECdyxAWs7X5wagW8XElydDMHa8QFnuGm93KqiHJK5HFXQLkNliNYRMKK3bxNTNgiacdccxw8OH05zyXgAkhmm+q4EvdlypyDqSglT2qHyQjG6XBBFwbqfwK2+fx8Q==
  template:
    metadata:
      creationTimestamp: null
      name: odysseus
      namespace: odysseus
---
