apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: searxng
  namespace: odysseus
spec:
  encryptedData:
    secret-key: AgC9dlzkQpgmlmE5peLHCQTxbEbKtSI+vPpvYIof3TAesJBbvWTUafB3KpI/Jn1OxDy57iXdg7i2fgLzAEBnfWtoxl1G6AB1ETjzibV2h39TrONwthwjNKahwnd2TUA+IKInVRkRRjBonyWbtM6euSzeXn1IlA1N4ka0b2r6A6oasjABxqb/pXyvVFzDeAMPxUUosQ8qcllCz+pClI9mNG9O1P755oBcYWEQspeffygiWNPAoJyvnJdOrEsAdpdMd7C++mm22asuaJRerFi84DR9QBOWiG3ixrAhHfCALJD0pY+oB7+7jmB2NWA5aNbNOOi/z90VscLtOQmo8paoWZ2huD4CQeGtssC+pV9LMB9rqhr6yn9htDmOytbQpkDmQsceEVDeNpPr3Sfag+YBqb83kZGUwZ18JfzwK24hBhdanNEPtPw5k5jdfAPDEjwySgDyRxLf/0ep5CAMCi7/GC3b1PYCnlPGdqIiJgBj/YHdBmuvbKw76eoT/Dmf5Gn9XFwlOAVpC2VDBAPEEH+o07XwOOFDFQYVNrrpyCoTXzSkzLck3kxoKMBKeZNns84552x++UCy9X4mOfShuyMFgBkIHgJFwMDPY/9WXDzu1fVGhA7hiIZXanKcO9ddQhLhGnhriT1eGaufqPkedGNEEbdzPsQSMQKPb2ORJwLEOmyZcNznq4XryPVdgZTtg2ODjBNF9HL+KmqKse2MvC0pYwUqA47QDyc7/ys/ynDEcex5ItEKeSQlkzgsP776Gbaj1VO19hXShaZcSVQwUWY=
  template:
    metadata:
      creationTimestamp: null
      name: searxng
      namespace: odysseus
---
