---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: paperless-data
  labels:
    app.kubernetes.io/name: paperless-ngx
spec:
  capacity:
    storage: 100Gi
  accessModes: ["ReadWriteOnce"]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: appdata
  hostPath:
    path: /mnt/appdata/paperless-ngx
    type: DirectoryOrCreate
  claimRef:
    namespace: docs
    name: paperless-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values: ["watchtower"]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-data
  namespace: docs
  labels:
    app.kubernetes.io/name: paperless-ngx
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: appdata
  volumeName: paperless-data
  resources:
    requests:
      storage: 100Gi
