apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tailscale
  namespace: kube-system
spec:
  encryptedData:
    authkey: AgAjJbo989c1HGyUZlFoYAbdErEZxCcQe5YCIHR+YPyTiGg7gJ2eZPxyvduRfmbQosina2ug8EOTK2yeLQYkqJo8trtlWgzOEDjHG7YcuDACzCRP3jglDp/5PNMJrmtVS/UMe2EumRSGWrLOvyLTfFwFmqmGMsGi9/p7mBK7MUQ0i7/CT5j+ziFreJxusEOT3dPFt1HG7x+uvAF3Kri299whnVbRRPLpd5osIOmBMDcmtteATMYCPLZX8DOzaWi2nsa9eZLS8TnGzzIRAJ4zFNFYnCj6DpN/JlEAPrc8LWWaXNZBM1gxw5OfxiTrnhHGbmu5yDhOLfZw8Q6X9BpgyL3jSK1xz83yY42zF4DWWO61SpRMLt4V3yI0OtJThiOx55CPI7J77FCGcQKl7kMU+vjpm59z9W7YIS2zsuAQWGjpf4Z/0QDqrphuvAPFebS4sk3KdqRwTDxNZFRGPpZpOcsPyLOSAr9Dm9LMy4azoGSPi1l1P7iOuelC7q3rtJQSlNLgUUIZqbnd4cJOtjbzSGnoixstB8RRzumxMx92Qi9qQ4/o/GsmoOzwlsAKDM4BbX0+M6WeJPMwpx0VQS8hA6OnRvEzMbkqcvIgdouS9yztFRoyVcVSnal+mBzHFNmigwTb0AfXBSUATRkyK08aBNVKtOfAiqcv2wckFZoPr1IolEwi2NLVmCJsm1XStaxmw66MaJzzfkxppL5KT8GFrLvcCmpqJt+8lyFuwwltMWNTaL6qTrWGWispZbHOnuHHEpRn43Uv982Hny8BDf4jkg1BivSZv5rxoUW1w+bj7v5bA5r4rdoR4kC+
  template:
    metadata:
      creationTimestamp: null
      name: tailscale
      namespace: kube-system
---
