---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vaultwarden-data
  labels:
    app.kubernetes.io/name: vaultwarden
spec:
  capacity:
    storage: 10Gi
  accessModes: ["ReadWriteOnce"]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: appdata
  hostPath:
    path: /mnt/appdata/vaultwarden
    type: DirectoryOrCreate
  claimRef:
    namespace: identity
    name: vaultwarden-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values: ["watchtower"]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-data
  namespace: identity
  labels:
    app.kubernetes.io/name: vaultwarden
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: appdata
  volumeName: vaultwarden-data
  resources:
    requests:
      storage: 10Gi
