apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: vaultwarden
  namespace: identity
spec:
  encryptedData:
    admin-token: AgB5Z6ZzOl5EKXrVWDRP4UpdmME0UWo3JsW3mJopbN8lclBxTi6MNxR47w7WZHTOWTQ2FtwOcQ7OXBohJWD3+FtBFBJ4hkTzFwIDkZ/PJEkrNPNayA2nGPrBK7ppES+kFSmB3OYuXjicSMCr4zQ0l6Nl30FnylZPnwxMqCoihCwrbx/mJ+BtUtgliTT44VfgZljtKWhPFpN8j0hywukpm+Oe4n/b6X0BIUCHFrOI/1Bjbtl2ppZce1fjDdEES+gBgPfL3GfPmzgXoRnJq6OkNsh6RUdhqAYcekS5NK096tH5VG0uSZTZvu/4LtyUD3vGk0/q0FQDaS52l3utF3cb29EkLHYIbsiOYZZMHr19yNsy0eqYnn/r/6OgnxTtTsT0FKbKea3pqQ/mX8a7IWJwQLAEHI5/7nBkYItEjJXrLt6xy6hHzYKLlVASv1XjkspeTJWdJR9C/j/wCOVw7FcwZq3g20XTFgVWO5r/3WjFeObLHeyC4JSGsfgMyJqem9z7TopQYUiBdsKtQ5wp6E3y4v1GJCXFmCeRi5I1pQwq9vS5o0yzg6hh3/2fXQGcRMVRSm4iWakdxWQUf9FoAPF4XFlUf3qJZe9SKsQuZX2PyYDAUr7IYDfNsLTLJPuKfmcRpHhRmRC/8Ib/z8oVV4AOIjXDjrcAOPefRHB/bndXz16B95IJdp+GvC4Jfugn0kGOa9NwJklwSd46FENNTnD8A1V3n7skE/o3vkf3Ag6cX31wW7YkyStGZov3kqnzbbDVaKrof/wR8/rTZm8a/N6bgTB4
    sso-client-secret: AgCoZYXVAE6AMB1IG9vqcdeZpxjWx1GX15uNdbN1Ti0gCPW/zXZkB5JtFVk3qQw1dxMuTE/FvRd+k/iR8dnBKhZeR8+xG/2cIgRQWsJMaLEAVcA12fT94wCc5msc7364GzkttZ8Fqi2ng3ctHGqkEu57s+DG8/A+JbJbODCz9zVOIuN/AqoaknMyIZD3DPoXdqRWJv5L7VpD3VHnvI4Q11ehJ1Ewca3kNBR7wxSdU/2iX+jOa6gWVYpWK1nIZ4VjD0jDD2zVQbf/XTc7SLdUhEg+cQqSRM8DY4d9kl0OYqJg0YWMq9HvOJqMsFLVbjx7n5Z98eOW8jqizQsJSrzGeqYZSmqd9dAKrzewuyTfqawwAPeoI4UgkYcn9HwM5gnIUjFNw4Z0XXc8fv1iF8AVLGGlkKUYYoCHJF6qVY50rvn7BBZ06I0ND8x0GHxHog/qnUWBXFuI2G+cZrlRbKUmK6hHqydzDaGBdYxj3sdak6ORA1zHbta3dYsEB28AcHEe38XwL+R6v+37mAvZFOVfGvQwpDWuHxapgVrBdtNJ2XLWpEK1nckBV9LTSjSyzya3r5MynCsMcsmTfKvc7nOIeHfl5RuauZi1rZsEQeRWE6cRaf2xfg24+jE+0/q1wRBFzV0cZtzfnMwWf3EGBBUdnrHPn4wxJ4UaUN1OgIB696ptJQK1dOrtZjFVyyaqcP7/EiVjns+2qYlGxOSpUe2Ioo0aB6mWigFjP6jyfhte+OkBzA==
  template:
    metadata:
      creationTimestamp: null
      name: vaultwarden
      namespace: identity
