apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: vaultwarden
  namespace: identity
spec:
  encryptedData:
    admin-token: AgB55MAEFO7pbf7cEjn3ZOGm1H9MExXAwWJrMxGSzvQYYKpbhyQLjFIVXayU/tZCdz/o6yD+2e7YakWd8FiMJGLrZ9cUxDRx2+MGmDRjvn3fUTz16OSed2vInts3Li30RGduVbb2X3i20pD3DNsJQyxKUcxUD8g3028V9OXr1X9Qz7lCXI8wu8uiGEAhxlEEznxFTyir/GPNIkIKiOpRG9kpB4sJi9p6gg2TApJ4QPpJXXhAEtB1qLEmUJTsczg/K5Lk1qwPBZDBDmlxtcmqxV8VE8DU6VbjTq5+2n9/kvLvSSr501Rt0Kb7mt5enbh4fuLvWnBd1ad7hch5dm1lpbfm1plGG2bbiSQPz6u3GTlbCoCWIyhMuPqL2UT1MBAHMiRIrDWMPmlmTjfSTuDpk/s/G4/jp8madWRnTZGSHVhEupYdQGKtikORU0ad+fXG3eRYKm8pjthd1LZC8xlC2Z+7enfX0QZcNhN9DnPaYMs1E9+ZnRZTvVPTAGj7Y2VHnPdf845kPHSDjssTxtKvxY+5tsVfzSLUJsF9eoByBIqsMWiv/rbOekG87GgQrqsnFtFSDdnU8TG8hcTZMR5h782sFMvE0bSyd9kcCdmY4G0KheB/TsKchKIloM8s7x1aLw/PEwRYrBgCNUGQAdi2RoPWyXA5hplT6KwPaFLm8MVHlKP9TRVRVKl1IxAVNiojMO2pc21v3U0ne4SAmB9Ey5p1kAjKOMnKdptL37gmZR5ugjzBCVJhSC5Z3iDLSWmpzeUTwBJCmef/oezilqN/aLVi
    sso-client-secret: AgCfXyMSu5GH4BDbZYuAWeig78MiTUm+eZcTfGqPezWj5llRUACbjBC2J4kF5M2Eu+znjcWaRUwWLQT0r2YVFsdiavEt8RajME2x5x3SRq+En/X8hRLMqWRG5Va5diGasqLJ/Hqu1gS7r2LoLOo2CbRWruNoKeQ1wDLcjKVC/zZlthHHoWMOu2LB54dITWENHRefSNThVI3ezUcvd8pijSeNFG+GSf4KXhTCUgMDx9ScAh39LjeYJsy25SKGko9lyc2M/DENrlCLEFEF2Mgl5+OjNYH+HVp3EBzgC55JRpbi/rbWV+vfLME4CbUB6RwsfCEaEAwEd8CcVYEeTWrDrQYZsLO+mqwkNqs0E33jwK1Gl5F1nL28m7LQ+d65wK85XUBQ0Lt8hy6PO1ssPs47upSxjO6Lz0c+UmuHrv6XbBaH7fywP+JQrNPul4Js0uy83kPZoQnFhvuQGC1U9KkXRUrOL2wyFOstBK1syuxb2eckz+Tf+coBQ3VBCGVQh8HTes403xZd9Wi617bo8Sy6lMDbzHxeKslgYR4tjsntolgw8jnOK+bDM+J1nb50xLNYRO8ax3eBfmBA3RaxWjlrBHKaNPadyaZuLL7AyYZ45mkxBScodx93HV3d6gPHmbV5gJzAl6cvMH/oFFlAvHoFhpbFWgwZbSwhEAfTSmOJWVQW58H6RyVrP8TxTA/qDMJf7qEDK4Il4XLTfJeKDLSNdrAUSX/uCgmAKN6FVK4bH6XT7Q==
  template:
    metadata:
      creationTimestamp: null
      name: vaultwarden
      namespace: identity
---
