apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: vaultwarden
  namespace: identity
spec:
  encryptedData:
    admin-token: AgBevNqF23IkRtJHnbyplwSmNSorEVdW881L9bklHx/QQcD4Ujwk3RWR1MKZ8CqoqRdd+B26dvFBktC5i59AweGui/iDSTxZx6qZH8g8bfDwDJGYPglbF290g6K0tQIg8o63v7jynIPpss2tjHdssGUEycMdtbxBXKMVwdLMYP9SjxeapxMMzPWcj/MP9MufY3sDZY5LLy+NEIJuCsRlu8ZBLjCZagBSaD0wer0eSVFZBvHVN2NdrqfbRnq7xbgGgybQm315qki6uJlGJ6htC1pnWVzAtw3iaraiFm21B4h9qT99FyNAoT83h4hgySlpDUii71y9U1FbljpwuTUvJOLcy35T5MGiDw2+weUVr/R/pxHbSofFF5aAotgijuL9t+MuhSZqdF82t+fksS1hR6A2H78W+8DAHsQQiDL7E2fvpSVFX2oRlJE+mP4lhijlgJviVy/ME2X9ZDMwm/xom5docmwoq9P2rCMjmr3gVClvTAo4/rXCaDEePtj/MHOtPANZYVcZh2uq1E605dwq1GZl9m/DOOnjtX+xaDfOnUpdaUamwc1Ssefl0QcDdnM1EkxbGZJlnq+CE0p0DGFrO/UxV4oXhJ5mTbTj9iDHpTZu/IXkvpr/d+WVjpjtCpvKSPL3fQFa2Y0nYMTsxU61h4NVatRakk+S9UuZuR3ypODhmgZ20JzU8dIMuVAGKk2VtHsEa0er/D87xXgb5pXOs8imqClmoEiZRiouFFivP6gOFEprJ70myDG6UZOmJHkFWSUy2MqLYI0sMEtf2czmS5+D
  template:
    metadata:
      creationTimestamp: null
      name: vaultwarden
      namespace: identity
---
