apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik-dashboard-auth
  namespace: kube-system
spec:
  encryptedData:
    users: AgAdqxfXMcj+0L2uYY7UDkMwtzHWY4bdxigD6/BDawxJGglUn91OqnBYmK0z30gz3mfXs/KUuv26Och2hM+1E/oev8SNrQVUpfnmhAzMkRKDZsx5kvw8jwdMxS6EPRyz3KvR5TAPjIO24pKwexaNV92avSygngVWEHcTImVDuFoTR+qsYrUTIEeqJmzeYfAKU57XZ3aJiyJoX9s1nkZqa0759KCgvMsR704GaptQrPawcUcbx/NbdrRsx7bC+Ry8jdZ7ACHm2+oZOq4p+rr4itA3Nv1+gmBBWX0NM78lE5PZxtA/GMaE9RcpiE5yofa2KAQrUPjThHW5bdg3MJ5AR9e2nGxBXNVtiuFad3cq5Xbv+Z08GGzoSk4hcbs4qb1jiDqjTBGhnCDngGNN6PfUn3dLo8X9wRwCMAWW7motLOAYD2jwDj26UcGrxBaMZNRtDQ7X+4+YlU2Fv+k8qdzD6xqNTZVdfzh69zPJ4G/qtSr/+ukeRiOaJP2lVDwxz73W6WijMrTBXlQfJ2BYfwCNs9Of+ue6WNl42+WIZxawmklsy3yLPSiq+BZXYsNU+zlYcJIuuMyndW7Bxy7R+mfHklnvd785+X658VwI6nJHiEX3AUezs3YcKF4inSq33rSur6m71q8XO+TLN8YDged+8NsFeM8rohk0l4zRByHEkRwJqZZHnfN1rdB5kr0P2AqffcPXC+JRdYo84QriMlLuJDRcq5apLdFVhlvkHh49mLuFwRpaU2CmGOg9tfM3
  template:
    metadata:
      creationTimestamp: null
      name: traefik-dashboard-auth
      namespace: kube-system
---
